security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Blogger\BlogBundle\Entity\Users:
          algorithm: sha512
          encode-as-base64: true
          iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: {class: Blogger\BlogBundle\Entity\Users, property: username}
        
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiPassPhrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          