<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogsRepository extends EntityRepository
{
    /**
     * Get all latest blogs
     * 
     * @return \Blogger\BlogBundle\Entity\Blogs
     */
    public function getLatestBlogs($user = NULL)
    {
        $criteria = array();
        
        if ($user !== NULL) {
            $criteria = array('user' => $user);
        }
        
        $blogs = $this->findBy($criteria, array("id" => 'DESC'));
        
        // by using the queryBuilder
//      $blogs = $this->createQueryBuilder()
//                  ->select('b')
//                  ->from('BloggerBlogBundle:Blogs','b')
//                  ->addOrderBy('b.createdAt', 'DESC')
//                  ->getQuery()
//                  ->getResult();
        
        return $blogs;
        
    }
}
