<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * 
     * @param integer $blogId
     * @param boolean $approved
     * @return array
     */
    public function getCommentsForBlog($blogId, $approved = true) 
    {
        $query =  $this->createQueryBuilder('c')
                        ->select('c')
                        ->where('c.blog = :blog_id')
                        ->addOrderBy('c.created', 'DESC')
                        ->setParameter('blog_id', $blogId);
        
        if (false == is_null($approved)) {
            $query->andWhere('c.approved = :approved')
                  ->setParameter('approved', $approved);  
        }
        
        return $query->getQuery()->getResult();
   }
}