<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function isValidUser($userObject)
    {
        $user =  $this->findOneBy(array('username' => $userObject->getUsername(),
            'password' => $userObject->getPassword()));
        
        return ($user)? $user: null;
    }
}
